[tool.ruff]
# Set the maximum line length to 79
line-length = 79
 
[tool.ruff.lint]
# By default, Ruff omits rules that overlap with the use of a formatter, like 
# Black, but we can override this behavior by explicitly adding the rule.
extend-select = [
  "E",
  "W",
  "N",
  "D",
  "UP",
]